task-2: add several utils for working with maps and slices
ozonva/ova-link-api pull request #2
Opened 2021-08-07 10:47 UTC by AleksandrCherepanov

2021-08-09 15:53 UTC, MrDniwe requested changes
Почти отлично, но нужно местами поправить

2021-08-09 15:53 UTC, MrDniwe commented on internal/utils/map.go
> +	}
Не понял зачем промежуточное складывание в массив и сортировка. Можно сразу брать ключи и значения исходного массива через `for key, value := range inputMap` и складывать в предварительно созданную новую мапу.

2021-08-09 15:53 UTC, MrDniwe commented on internal/utils/map_test.go
> +import "testing"
Похвально, конечно! Но тесты будут в следующем задании. Но пусть остаются)

2021-08-09 15:53 UTC, MrDniwe commented on internal/utils/slice.go
> +	result := make([][]int, 0, sliceLength/size)
Тут напрашивается некоторая поправка: при делении интов будет отброшен остаток от деления, иными словами произойдет округление вниз. То есть 16/5 = 3 к примеру. А у нас при таком раскладе нужно по-хорошему зарезирвировать ещё одно место в массиве для "хвоста", то есть округлять вверх. Иначе на последнем append произойдёт повторный allocation памяти для массива на неоправданно большое количество элементов. Это дорого и нам ни к чему.

2021-08-09 15:53 UTC, MrDniwe commented on internal/utils/slice.go
> +}
Интересный вариант с мемоизирующей оптимизацией, прям порадовался. Но в худшем случае он отработает как O(m*n). А вот если например изначально положить в мапу фильтрующий слайс и потом обращаться к этой мапе для проверки, то получилось бы О(n).
Но будем считать за зачёт!

2021-08-09 17:34 UTC, AleksandrCherepanov commented on internal/utils/map.go
> +	}
да, можно) но когда я писал тесты возникла ситуация, что проход по мапе он же не гарантирует порядок ключей и у меня был выбор, пытаться в тестах с этим бороться, либо всегд гарантировать что ключи будут отсортированы в результирующей мапе, если это излишне, могу убрать

2021-08-09 17:35 UTC, AleksandrCherepanov commented on internal/utils/slice.go
> +}
Интересно, почему-то не пришло в голову это решение, тогда не пришлось бы и бинарный поиск писать, спасибо)

2021-08-09 17:37 UTC, AleksandrCherepanov commented on internal/utils/slice.go
> +	result := make([][]int, 0, sliceLength/size)
Правильно ли я понимаю, что достаточно будет просто добавлять едницу к размеру после деления?

2021-08-11 11:35 UTC, MrDniwe requested changes
Всё-таки настаиваю на правке алгоритма инвертирования мапы

2021-08-11 13:22 UTC, MrDniwe approved these changes
Всё ок!

2021-08-11 16:01 UTC, merged