Feature/task 4
ozonva/ova-link-api pull request #4
Opened 2021-08-21 11:54 UTC by AleksandrCherepanov

2021-08-23 20:45 UTC, MrDniwe requested changes
Похвальный рефакторинг тестов! Да и вообще в целом всё норм. Хотелось бы разве что вот что: нужна команда make на генерацию моков, поскольку это довольно часто запускаемое событие. И, вероятно, так же команда make на установку сопутствующих бинарников, таких как ginkgo - например внутрь проекта в папку прописанную в .gitignore

2021-08-23 20:45 UTC, MrDniwe commented on internal/mockgen.go
> +//go:generate mockgen -destination=./mocks/repo_mock.go -package=mocks github.com/ozonva/ova-link-api/internal/repo Repo
Странный файл от mockgen. А без него никуда?

2021-08-24 02:29 UTC, AleksandrCherepanov commented on internal/mockgen.go
> +//go:generate mockgen -destination=./mocks/repo_mock.go -package=mocks github.com/ozonva/ova-link-api/internal/repo Repo
Насколько я понял из урока, это подход к организации генерации моков. Т.е. это не файл от mockgen, а просто файл так назван и в нем прописываются таким образом правила для генерации моков. А затем командой `go generate` геерируется и она подхватывает эти правила

2021-08-24 10:43 UTC, MrDniwe commented on internal/mockgen.go
> +//go:generate mockgen -destination=./mocks/repo_mock.go -package=mocks github.com/ozonva/ova-link-api/internal/repo Repo
Ок, я просто другим мок-генератором пользуюсь, мне было необычно

2021-08-24 10:49 UTC, MrDniwe approved these changes
👍

2021-08-24 10:57 UTC, merged