task-5: Add timeout saver
ozonva/ova-link-api pull request #5
Opened 2021-08-21 13:18 UTC by AleksandrCherepanov

2021-08-23 21:08 UTC, MrDniwe requested changes
В целом направление движения верное, предлагаю чуть обширнее помыслить в сторону каналов. Если что - задавай вопросы.

2021-08-23 21:08 UTC, MrDniwe commented on internal/saver/saver.go
> +		}
Вот это хорошее начало. Я бы развил тему с каналами. Можно для начала for сделать просто вечным безусловным, выкинув параметр timerAlive из кода совсем. А в select слушать следующие каналы:
1. при приходе сигнала в канал тикера делаем flush (это уже есть)
2. сделать чтоб метод save не аппендил элемент в массив, а отправлял данные в соответствующий канал, а в этом селекте мы будем ловить эти данные из канала и делать append
3. сделать чтоб метод close отправлял сигнал в некий информационный "канал закрытия", а здесь мы его в селекте ловим и далее последовательно: останавниваем тикер, флашим данные, выходим из цикла (и горутины)

Таким образом, у нас получится этакий воркер, который следит за всем очень конкурентно и компактно.

2021-08-25 13:10 UTC, MrDniwe approved these changes
Всё норм

2021-08-25 13:10 UTC, MrDniwe commented on internal/saver/saver.go
> +}
По сути мютексы тут не нужны. У нас воркер стартует всегда один, и одновременно делает только одну операцию в select, так что ситуация с одновременным запуском flush() и addToFlush() исключена. Если только не планируется их запускать в отдельных горутинах.

2021-08-25 14:03 UTC, AleksandrCherepanov commented on internal/saver/saver.go
> +}
Понял, убрал

2021-08-25 14:05 UTC, merged