Feature/task 7
ozonva/ova-link-api pull request #7
Opened 2021-08-29 14:20 UTC by AleksandrCherepanov

2021-08-30 14:21 UTC, MrDniwe requested changes
В целом всё ок, без приминала. Немного правок и тесты.

2021-08-30 14:21 UTC, MrDniwe commented on Makefile
> +	rm /tmp/psql_user.sql
Это как-то диковато. Можно сделать просто через ключи при старте контейнера (см. перменные окружения в https://hub.docker.com/_/postgres) или залить аналогичный скрипт в `/docker-entrypoint-initdb.d` внутри контейнера

2021-08-31 16:11 UTC, AleksandrCherepanov commented on migrations/20210828132137_create_link_table.sql
> +);
done

2021-08-31 16:11 UTC, AleksandrCherepanov commented on migrations/20210828135218_index_for_user_select.sql
> +CREATE INDEX IF NOT EXISTS idx_user ON links (user_id);
done

2021-08-31 16:11 UTC, AleksandrCherepanov commented on Makefile
> +	rm /tmp/psql_user.sql
done

2021-09-02 12:04 UTC, MrDniwe approved these changes
👍

2021-09-02 12:14 UTC, merged